# -*- coding: utf-8 -*-
"""Breast Cancer Wisnconsin (Diagnostic) Data Set [Kawu Musa "Mufasa", 29.05.2023].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uu9FiF7NiPwLqekoVnTZ-fVo8KYZkDny

# Pre-processing of Breast Cancer Wisconsin (Diagnostic) Data Set

Link: https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data

## Step 1 - Importing Libraries and Dataset
"""

import pandas as pd
import seaborn as sbn
import matplotlib.pyplot as plt

#reading csv file using pandas and saving into a variable called 'data'
data = pd.read_csv('/content/data.csv')

#previewing the top 5 rows in the dataset
data.head()

"""## Step 2 - Data Exploration"""

#Finding out the number of rows and columns in the dataset
data.shape

#Obtaining basic information about the dataset
data.info()

#Finding the column that has categorical (Non-numerical) data.
data.select_dtypes(include='object').columns

#Finding the number of column(s) that have/has categorical (Non-numerical) data.
len(data.select_dtypes(include='object').columns)

#Finding the column(s) that have / has numerical data.
data.select_dtypes(include=['float64','int64']).columns

#Finding the number of column(s) that have / has numerical data.
len(data.select_dtypes(include=['float64','int64']).columns)

#Summarising statistical information about the columns in the dataset.
data.describe()

"""## Step 3 - Dealing with the missing values"""

#Are there null values in the dataset?
data.isnull().values.any()

#The number of null values in the dataset?
data.isnull().values.sum()

#What column has the null values?
data.columns[data.isnull().any()]

#The number of columns with null values.
len(data.columns[data.isnull().any()])

data['Unnamed: 32'].count()

#drop the column with the null values
data = data.drop(columns='Unnamed: 32')

#Find the shape after dropping that column
data.shape

#are there any more null values in the data
data.isnull().values.any()

"""## Step 4 - Dealing with categorical data"""

#Identify the column with categorical data
data.select_dtypes(include='object').columns

#Identify unique values in the 'diagnosis' column
data['diagnosis'].unique()

#The number of unique values in the 'diagnosis' column
data['diagnosis'].nunique()

#Encode categorical data as 0 and 1
#One hot encoding
data = pd.get_dummies(data=data,drop_first=True)

#Show the top 5 rows
data.head()