# -*- coding: utf-8 -*-
""""Daily Power Generation in India (2017-2020)" [06.05.2023].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vhb4Uuz6F2JQHBJJFscrBwy3ukt07mrz

#Pre-processing of "Daily Power Generation in India (2017-2020)" - Mufasa

Link: https://www.kaggle.com/datasets/navinmundhra/daily-power-generation-in-india-20172020

## Step 1 - Importing Libraries and Dataset
"""

import pandas as pd
import seaborn as sbn
import matplotlib.pyplot as plt

#Reading csv file using pandas and saving it as a variable "data_set"
data_set = pd.read_csv("file_02.csv")

#Previewing the TOP 5 rows in the Dataset
data_set.head()

"""## Step 2 - Data Exploration"""

#The Number of rows and columns in the Dataset; (4945 rows, 9 columns)

data_set.shape

#Basic information about the Dataset

data_set.info()

#Columns with non-numerical variables
data_set.select_dtypes(include='object').columns

#Number of columns with non-numerical variables ; 4
len(data_set.select_dtypes(include='object').columns)

#Columns with numerical variables
data_set.select_dtypes(include=['float64','int64']).columns

#Columns with numerical variables ;  5
len(data_set.select_dtypes(include=['float64','int64']).columns)

#Summarising the columns of the dataset statistically
data_set.describe()

"""## Step 3 - Dealing with missing values"""

#Checking for null values in the Data Set; There are null values
data_set.isnull().values.any()

#The total count of null values in the Dataset; 3956
data_set.isnull().values.sum()

#Columns with the null values in the Dataset; Two columns "Nuclear Generation Actual (in MU)" and "Nuclear Generation Estimated (in MU)"
data_set.columns[data_set.isnull().any()]

#Number of Columns with the null values in the Dataset; Two columns
len(data_set.columns[data_set.isnull().any()])

#Number of rows in the "Nuclear Generation Actual (in MU)" that are null
data_set['Nuclear Generation Actual (in MU)'].count()

#Number of rows in the "Nuclear Generation Estimate (in MU)" that are null
data_set['Nuclear Generation Estimated (in MU)'].count()

"""## Step 4 - Dealing with categorical data"""

#Columns with non-numerical variables; "Region" is the critical column
data_set.select_dtypes(include='object').columns

#Identifying the unique categories in the 'Region' column
data_set['Region'].unique()

#Identifying the number of unique categories in the 'Region' column; 5 columns
data_set['Region'].nunique()

#A countplot of the Region column
sbn.countplot(x ='Region', data = data_set)

#Encoding Categorical Data as 0 and 1
data_set = pd.get_dummies(data=data_set,columns=['Region'])

data_set.head()

