# -*- coding: utf-8 -*-
""""Imports of Crude Oil and Petroleum Products into the United States by Country of Origin, March 2023" [12.06.2023].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vhb4Uuz6F2JQHBJJFscrBwy3ukt07mrz

#Pre-processing of "Imports of Crude Oil and Petroleum Products into the United States by Country of Origin, March 2023" [12.06.2023] - Mufasa

Link: https://www.eia.gov/petroleum/supply/monthly/csv/table39.csv

## Step 1 - Importing Libraries and Dataset
"""

import pandas as pd
import seaborn as sbn
import matplotlib.pyplot as plt

#Reading csv file using pandas and saving it as a variable "data_set"
data_set = pd.read_csv("table39.csv",encoding='cp1252')

#Previewing the TOP 5 rows in the Dataset
data_set.head()

"""## Step 2 - Data Exploration"""

#The Number of rows and columns in the Dataset; (61 rows, 41 columns)

data_set.shape

#Basic information about the Dataset

data_set.info()

#Columns with non-numerical variables; Seems all columns entail non-integers.
data_set.select_dtypes(include='object').columns

#Number of columns with non-numerical variables ; 41
len(data_set.select_dtypes(include='object').columns)

#Columns with numerical variables; None
data_set.select_dtypes(include=['float64','int64']).columns

#Columns with numerical variables ;  0
len(data_set.select_dtypes(include=['float64','int64']).columns)

#Summarising the columns of the dataset statistically
data_set.describe()

"""## Step 3 - Dealing with missing values"""

#Checking for null values in the Data Set; There aren't null values
data_set.isnull().values.any()

#The total count of null values in the Dataset; 0
data_set.isnull().values.sum()

"""## Bonus - How much Crude Oil was imported from OPEC?"""

#Viewing the Crude oil column
data_set['Crude     Oil']

#Viewing the OPEC row; OPEC exported 34.7 million bbls of Crude Oil to the US in March 2023
data_set.loc[(data_set['STUB_1']=="OPEC")].sum()

